server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: demo-queue
          group: producer-consumer
          binder: rabbit
          consumer:
            autoBindDlq: true
            republishToDlq: true
            requeueRejected: false
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${vcap.services.p-rabbitmq.amqp.host}
                port: 5672
                username: ${vcap.services.p-rabbitmq.amqp.username}
                password: ${vcap.services.p-rabbitmq.amqp.password}